name: Testing Example Applications

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ["express-pg-auth0", "express-pg-jwt", "nest-mongo-auth0", "nest-mongo-jwt", "nest-pg-auth0", "nest-pg-jwt"]
      max-parallel: 1

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
        ports: ["5432:5432"]

      mongo:
        image: mongo:latest
        ports: ["27017:27017"]
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Clean npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: |
        git init
        npm install
      working-directory: ${{ matrix.project }}

    - name: Create .env.test file
      run: |
        mv .env.example .env.test

        sed -i 's/NODE_ENV=.*/NODE_ENV=test/g' .env.test
        sed -i 's/PORT=.*/PORT=3000/g' .env.test

        sed -i 's/ERROR_LOGGING=.*/ERROR_LOGGING=false/g' .env.test
        sed -i 's/REQUEST_LOGGING=.*/REQUEST_LOGGING=false/g' .env.test
        sed -i 's/SWAGGER=.*/SWAGGER=false/g' .env.test

        sed -i 's/PGHOST=.*/PGHOST=0.0.0.0/g' .env.test
        sed -i 's/PGPORT=.*/PGPORT=5432/g' .env.test
        sed -i 's/PGUSER=.*/PGUSER=postgres/g' .env.test
        sed -i 's/PGPASSWORD=.*/PGPASSWORD=password/g' .env.test
        sed -i 's/PGDATABASE=.*/PGDATABASE=test/g' .env.test

        sed -i 's/MONGO_PROTOCOL=.*/MONGO_PROTOCOL=mongodb/g' .env.test
        sed -i 's/MONGO_HOST=.*/MONGO_HOST=localhost/g' .env.test
        sed -i 's/MONGO_PORT=.*/MONGO_PORT=27017/g' .env.test
        sed -i 's/MONGO_USER=.*/MONGO_USER=root/g' .env.test
        sed -i 's/MONGO_PASSWORD=.*/MONGO_PASSWORD=password/g' .env.test
        sed -i 's/MONGO_DATABASE_NAME=.*/MONGO_DATABASE_NAME=example-app/g' .env.test
      working-directory: ${{ matrix.project }}

    - name: Run tests
      run: npm run test:unit
      working-directory: ${{ matrix.project }}

    - name: Run end-to-end tests
      run: npm run test:e2e
      working-directory: ${{ matrix.project }}